const CFG=window.CELLAR_CONFIG||{};
const configured=CFG.SUPABASE_URL&&!CFG.SUPABASE_URL.includes('PASTE_')&&CFG.SUPABASE_ANON_KEY&&!CFG.SUPABASE_ANON_KEY.includes('PASTE_');
const db=configured?supabase.createClient(CFG.SUPABASE_URL,CFG.SUPABASE_ANON_KEY):null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let user=null,household=null,wines=[],activity=[],reader=null,controls=null,labelFile=null,bottlePhotoFile=null,lastFastCorkRaw=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n||0));
const stars=n=>`<span class="stars">${'★'.repeat(Math.round(Number(n||0)))}${'☆'.repeat(5-Math.round(Number(n||0)))}</span>`;
function toast(m){const t=$('#toast');if(!t)return;t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3000)}
function openD(id){const d=$('#'+id);if(d&&!d.open)d.showModal()}
async function closeD(id){if(id==='scanDialog')await stopScan();const d=$('#'+id);if(d?.open)d.close()}
$$('[data-close]').forEach(b=>b.onclick=()=>closeD(b.dataset.close));

async function boot(){
 if(!configured){$('#configAlert')?.classList.remove('hidden');return}
 const {data:{session}}=await db.auth.getSession();if(session)await enter(session.user);
 db.auth.onAuthStateChange(async(_,s)=>{if(s?.user&&user?.id!==s.user.id)await enter(s.user);if(!s){user=null;$('#app')?.classList.add('hidden');$('#auth')?.classList.remove('hidden')}})
}
$('#loginForm').onsubmit=async e=>{e.preventDefault();const btn=e.submitter;btn.disabled=true;btn.textContent='Signing in…';const {error}=await db.auth.signInWithPassword({email:$('#loginEmail').value.trim(),password:$('#loginPassword').value});btn.disabled=false;btn.textContent='Sign in';if(error)toast(error.message)};
$('#logout').onclick=()=>db.auth.signOut();
async function enter(u){user=u;$('#auth').classList.add('hidden');$('#app').classList.remove('hidden');$('#signedInAs').textContent=u.email;$('#userId').textContent=u.id;await load();testFastCork()}
async function load(){
 const hm=await db.from('household_members').select('household_id,households(name)').eq('user_id',user.id).limit(1).maybeSingle();
 if(hm.error){toast('Database setup error: '+hm.error.message);return} household=hm.data;
 if(!household){wines=[];activity=[];render();toast('This user has not been added to a household');return}
 const [wr,ar]=await Promise.all([db.from('wines').select('*').eq('household_id',household.household_id).order('created_at',{ascending:false}),db.from('inventory_transactions').select('*').eq('household_id',household.household_id).order('created_at',{ascending:false}).limit(25)]);
 if(wr.error){toast(wr.error.message);return}wines=wr.data||[];activity=ar.data||[];render()
}
function view(n){$$('.view').forEach(x=>x.classList.remove('active'));$('#'+n+'View')?.classList.add('active');$$('nav [data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===n));if(n==='recommend')renderRecommendations()}
$$('[data-view]').forEach(b=>b.onclick=()=>view(b.dataset.view));
function card(w){const img=w.image_url?`<img class="thumb" src="${esc(w.image_url)}" alt="Bottle">`:'<div class="thumb">🍷</div>';return `<button class="wine-card" data-wine="${w.id}">${img}<div><p class="eyebrow">${esc(w.producer||w.wine_type||'WINE')}</p><h3>${esc(w.name)}</h3><p>${esc([w.vintage,w.varietal,w.region].filter(Boolean).join(' · '))}</p>${stars(w.personal_rating)}</div><div class="side"><span class="badge">${w.quantity} left</span><p><b>${money(w.estimated_price||w.purchase_price)}</b></p></div></button>`}
function render(){const bottles=wines.reduce((a,w)=>a+Number(w.quantity||0),0),val=wines.reduce((a,w)=>a+Number(w.quantity||0)*Number(w.estimated_price||w.purchase_price||0),0),low=wines.filter(w=>w.quantity<w.target_quantity);$('#bottleCount').textContent=bottles;$('#wineCount').textContent=wines.filter(w=>w.quantity>0).length;$('#cellarValue').textContent=money(val);$('#lowList').innerHTML=low.slice(0,3).map(card).join('')||'<div class="panel muted">Nothing is below target.</div>';$('#activity').innerHTML=activity.slice(0,5).map(a=>`<div class="activity"><b>${esc(a.transaction_type)}</b> ${Math.abs(a.quantity_change)} bottle(s)<br><small class="muted">${new Date(a.created_at).toLocaleString()} · ${esc(a.notes||'')}</small></div>`).join('')||'<div class="panel muted">No activity yet.</div>';renderCellar();renderShopping();bindCards()}
function renderCellar(){const q=$('#search').value.toLowerCase(),t=$('#type').value;const list=wines.filter(w=>(t==='All'||w.wine_type===t)&&[w.name,w.producer,w.region,w.varietal,w.upc].join(' ').toLowerCase().includes(q));$('#wineList').innerHTML=list.map(card).join('')||'<div class="panel muted">No matching wines.</div>';bindCards()}
$('#search').oninput=renderCellar;$('#type').onchange=renderCellar;
function bindCards(){$$('[data-wine]').forEach(b=>b.onclick=()=>detailWine(b.dataset.wine))}
function renderShopping(){const low=wines.filter(w=>w.quantity<w.target_quantity);$('#shoppingList').innerHTML=low.map(w=>`<div class="shop-card"><span class="badge">BUY ${w.target_quantity-w.quantity}</span><h3>${esc(w.producer||'')} ${esc(w.name)}</h3><p>Have ${w.quantity} · Target ${w.target_quantity} · ${money(w.estimated_price||w.purchase_price)} each</p><button class="secondary" data-addone="${w.id}">Add one</button></div>`).join('')||'<div class="panel muted">The fridge is stocked.</div>';$$('[data-addone]').forEach(b=>b.onclick=()=>adjust(b.dataset.addone,1,'restocked'))}
$('#copyList').onclick=async()=>{const low=wines.filter(w=>w.quantity<w.target_quantity),txt=low.map(w=>`${w.target_quantity-w.quantity} x ${w.producer||''} ${w.name} (${money(w.estimated_price||w.purchase_price)})`).join('\n')||'Wine fridge is stocked.';await navigator.clipboard.writeText(txt);toast('Shopping list copied')};

function resetForm(){lastFastCorkRaw=null;$('#wineForm').reset();bottlePhotoFile=null;$('#bottlePhotoPreview').classList.add('hidden');$('#bottlePhotoFrame>span').classList.remove('hidden');$('#photoStatus').textContent='A compressed bottle photo will be stored securely in Supabase Storage.';$('#advancedForm')?.classList.add('hidden');if($('#toggleAdvancedForm'))$('#toggleAdvancedForm').textContent='Show additional wine information';$('#wineId').value='';$('#imageUrl').value='';$('#quantity').value=1;$('#target').value=2;$('#deleteWine').classList.add('hidden')}
function setVal(id,v){const e=$('#'+id);if(e)e.value=v??''}
function editWine(w=null){resetForm();if(w){$('#wineFormTitle').textContent='Edit wine';const vals={wineId:w.id,imageUrl:w.image_url,wineName:w.name,producer:w.producer,vintage:w.vintage,wineType:w.wine_type,varietal:w.varietal,country:w.country,region:w.region,upc:w.upc,rack:w.rack_location,quantity:w.quantity,target:w.target_quantity,purchasePrice:w.purchase_price,estimatedPrice:w.estimated_price,rating:w.personal_rating,source:w.external_source,body:w.body_score,sweetness:w.sweetness_score,acidity:w.acidity_score,tannin:w.tannin_score,flavors:(w.flavor_tags||[]).join(', '),notes:w.personal_notes,appellation:w.appellation,alcoholPercentage:w.alcohol_percentage,servingTemperature:w.serving_temperature,decantingMinutes:w.decanting_minutes,recognitionConfidence:w.recognition_confidence,tastingNotes:w.tasting_notes,foodPairings:(w.food_pairings||[]).join('\n'),servingGuidance:w.serving_guidance};Object.entries(vals).forEach(([k,v])=>setVal(k,v));$('#deleteWine').classList.remove('hidden');if(w.image_url){$('#bottlePhotoPreview').src=w.image_url;$('#bottlePhotoPreview').classList.remove('hidden');$('#bottlePhotoFrame>span').classList.add('hidden')}}else $('#wineFormTitle').textContent='Add wine';openD('wineDialog')}
$('#toggleAdvancedForm').onclick=()=>{const hidden=$('#advancedForm').classList.toggle('hidden');$('#toggleAdvancedForm').textContent=hidden?'Show additional wine information':'Hide additional wine information'};
async function compressPhoto(file){return new Promise((resolve,reject)=>{const img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{const max=1400,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);c.toBlob(b=>{URL.revokeObjectURL(url);b?resolve(b):reject(new Error('Photo compression failed'))},'image/jpeg',.82)};img.onerror=reject;img.src=url})}
async function uploadBottlePhoto(wineId,file){const blob=await compressPhoto(file),path=`${household.household_id}/${wineId}/${Date.now()}.jpg`;const r=await db.storage.from('wine-images').upload(path,blob,{contentType:'image/jpeg',upsert:true});if(r.error)throw r.error;return db.storage.from('wine-images').getPublicUrl(path).data.publicUrl}
function chooseBottlePhoto(file){if(!file)return;bottlePhotoFile=file;$('#bottlePhotoPreview').src=URL.createObjectURL(file);$('#bottlePhotoPreview').classList.remove('hidden');$('#bottlePhotoFrame>span').classList.add('hidden');$('#photoStatus').textContent='Photo ready. It will upload when saved.'}
$('#bottlePhotoCamera').onchange=e=>chooseBottlePhoto(e.target.files[0]);$('#bottlePhotoLibrary').onchange=e=>chooseBottlePhoto(e.target.files[0]);
$('#wineForm').onsubmit=async e=>{e.preventDefault();if(!household)return toast('No household membership');const id=$('#wineId').value,p={household_id:household.household_id,created_by:user.id,name:$('#wineName').value.trim(),producer:$('#producer').value.trim(),vintage:$('#vintage').value.trim(),wine_type:$('#wineType').value,varietal:$('#varietal').value.trim(),country:$('#country').value.trim(),region:$('#region').value.trim(),upc:$('#upc').value.replace(/\D/g,'')||null,rack_location:$('#rack').value.trim(),quantity:Number($('#quantity').value),target_quantity:Number($('#target').value),purchase_price:Number($('#purchasePrice').value)||null,estimated_price:Number($('#estimatedPrice').value)||null,personal_rating:Number($('#rating').value),external_source:$('#source').value.trim(),body_score:Number($('#body').value),sweetness_score:Number($('#sweetness').value),acidity_score:Number($('#acidity').value),tannin_score:Number($('#tannin').value),flavor_tags:$('#flavors').value.split(',').map(x=>x.trim()).filter(Boolean),personal_notes:$('#notes').value.trim(),appellation:$('#appellation')?.value.trim()||'',alcohol_percentage:Number($('#alcoholPercentage')?.value)||null,serving_temperature:$('#servingTemperature')?.value.trim()||'',decanting_minutes:Number($('#decantingMinutes')?.value)||null,recognition_confidence:Number($('#recognitionConfidence')?.value)||null,tasting_notes:$('#tastingNotes')?.value.trim()||'',food_pairings:($('#foodPairings')?.value||'').split(/\n|,/).map(x=>x.trim()).filter(Boolean),serving_guidance:$('#servingGuidance')?.value.trim()||'',recognition_provider:lastFastCorkRaw?'FastCork':($('#source').value.trim()||null),recognized_at:lastFastCorkRaw?new Date().toISOString():null,fastcork_raw_data:lastFastCorkRaw,image_url:$('#imageUrl').value||null,updated_at:new Date().toISOString()};const r=id?await db.from('wines').update(p).eq('id',id).select().single():await db.from('wines').insert(p).select().single();if(r.error)return toast(r.error.message);const savedId=id||r.data.id;if(bottlePhotoFile){try{const url=await uploadBottlePhoto(savedId,bottlePhotoFile);await db.from('wines').update({image_url:url,updated_at:new Date().toISOString()}).eq('id',savedId)}catch(err){toast('Wine saved, but photo failed: '+err.message)}}if(!id)await logTx(savedId,p.quantity,'added',p.name);closeD('wineDialog');await load();toast(id?'Wine updated':'Wine added')};
$('#deleteWine').onclick=async()=>{const id=$('#wineId').value;if(!id||!confirm('Delete this wine?'))return;const {error}=await db.from('wines').delete().eq('id',id);if(error)return toast(error.message);closeD('wineDialog');await load();toast('Wine deleted')};

function detailWine(id){const w=wines.find(x=>x.id===id),pair=(w.food_pairings||[]).map(x=>`<span class="badge">${esc(x)}</span>`).join(' ');$('#detail').innerHTML=`<div class="dialog-head"><div><p class="eyebrow">${esc(w.producer||w.wine_type)}</p><h2>${esc(w.name)}</h2></div><button onclick="document.querySelector('#detailDialog').close()">×</button></div>${w.image_url?`<img class="detail-photo" src="${esc(w.image_url)}" alt="Bottle photo">`:''}<div class="detail-hero"><p>${esc([w.vintage,w.varietal,w.region].filter(Boolean).join(' · '))}</p><h2>${stars(w.personal_rating)}</h2><p>${esc(w.personal_notes||'No personal notes yet.')}</p></div><div class="detail-stats"><div><b>${w.quantity}</b><span>IN FRIDGE</span></div><div><b>${money(w.estimated_price||w.purchase_price)}</b><span>PRICE</span></div><div><b>${esc(w.rack_location||'—')}</b><span>RACK</span></div></div><p class="muted">UPC ${esc(w.upc||'not entered')}</p><div class="detail-actions"><button class="secondary" id="editDetail">Edit</button><button class="primary" id="consumeDetail" ${w.quantity<1?'disabled':''}>Consume one</button><button class="secondary" id="addDetail">Add one</button><button class="secondary" id="moreDetail">More wine details</button></div><div id="moreDetailsPanel" class="more-details hidden"><div class="details-section"><h3>Wine profile</h3><p><b>Appellation:</b> ${esc(w.appellation||'Not provided')}</p><p><b>Alcohol:</b> ${esc(w.alcohol_percentage?`${w.alcohol_percentage}%`:'Not provided')}</p><p><b>Grapes:</b> ${esc(w.varietal||'Not provided')}</p></div><div class="details-section"><h3>Tasting profile</h3><p>${esc(w.tasting_notes||'Not provided')}</p></div><div class="details-section"><h3>Serving guidance</h3><p><b>Temperature:</b> ${esc(w.serving_temperature||'Not provided')}</p><p><b>Decanting:</b> ${esc(w.decanting_minutes!=null?`${w.decanting_minutes} minutes`:'Not provided')}</p><p>${esc(w.serving_guidance||'')}</p></div><div class="details-section"><h3>Food pairings</h3><div>${pair||'<span class="muted">No pairings saved.</span>'}</div></div><div class="details-section"><h3>Source</h3><p>${esc(w.recognition_provider||w.external_source||'Manual entry')}</p></div></div>`;openD('detailDialog');$('#editDetail').onclick=()=>{closeD('detailDialog');editWine(w)};$('#consumeDetail').onclick=async()=>{await adjust(w.id,-1,'consumed');closeD('detailDialog')};$('#addDetail').onclick=async()=>{await adjust(w.id,1,'restocked');closeD('detailDialog')};$('#moreDetail').onclick=()=>{const hidden=$('#moreDetailsPanel').classList.toggle('hidden');$('#moreDetail').textContent=hidden?'More wine details':'Hide wine details'}}
async function logTx(wineId,delta,type,note){return db.from('inventory_transactions').insert({household_id:household.household_id,user_id:user.id,wine_id:wineId,transaction_type:type,quantity_change:delta,notes:note})}
async function adjust(id,d,type){const w=wines.find(x=>x.id===id);if(!w||w.quantity+d<0)return;const {error}=await db.from('wines').update({quantity:w.quantity+d,updated_at:new Date().toISOString()}).eq('id',id);if(error)return toast(error.message);await logTx(id,d,type,w.name);await load();toast(d>0?'Bottle added':'Bottle consumed')}

async function startScan(){openD('scanDialog');$('#scanStatus').textContent='Starting rear camera…';if(!window.ZXing){$('#scanStatus').textContent='ZXing did not load. Use manual UPC entry.';return}reader=new ZXing.BrowserMultiFormatReader();try{const devices=await reader.listVideoInputDevices(),sel=$('#cameraSelect');sel.innerHTML=devices.map((d,i)=>`<option value="${esc(d.deviceId)}">${esc(d.label||`Camera ${i+1}`)}</option>`).join('');const rear=devices.find(d=>/back|rear|environment/i.test(d.label))||devices[devices.length-1];sel.value=rear?.deviceId||'';await decode(rear?.deviceId);sel.onchange=async()=>{await stopScan(false);reader=new ZXing.BrowserMultiFormatReader();await decode(sel.value)}}catch(e){$('#scanStatus').textContent='Camera error: '+e.message}}
async function decode(deviceId){$('#scanStatus').textContent='Aim at a UPC-A, UPC-E, EAN-8, or EAN-13 barcode.';controls=await reader.decodeFromVideoDevice(deviceId,$('#scannerVideo'),async result=>{if(result){const code=result.getText();$('#scanStatus').textContent=`Scanned ${code}. Looking up…`;await stopScan(false);await lookup(code)}})}
async function stopScan(clear=true){try{controls?.stop()}catch{}try{reader?.reset()}catch{}controls=null;reader=null;if(clear&&$('#scannerVideo'))$('#scannerVideo').srcObject=null}
async function lookup(code){code=String(code).replace(/\D/g,'');if(![8,12,13].includes(code.length))return toast('UPC/EAN should be 8, 12, or 13 digits');const own=wines.find(w=>w.upc===code);if(own){closeD('scanDialog');await adjust(own.id,1,'restocked');return toast('Matched your cellar and added one bottle')}const endpoints=[['Open Food Facts',`https://world.openfoodfacts.org/api/v2/product/${code}.json?fields=product_name,brands,countries,origins,image_front_url`],['Open Products Facts',`https://world.openproductsfacts.org/api/v2/product/${code}.json?fields=product_name,brands,countries,origins,image_front_url`]];let product=null,source='';for(const [name,url] of endpoints){try{const r=await fetch(url),j=await r.json();if(j.status===1&&j.product?.product_name){product=j.product;source=name;break}}catch{}}closeD('scanDialog');editWine();setVal('upc',code);if(product){setVal('wineName',product.product_name);setVal('producer',(product.brands||'').split(',')[0]);setVal('country',(product.countries||'').split(',')[0]);setVal('region',product.origins||'');setVal('imageUrl',product.image_front_url||'');setVal('source',source);toast(`Found in ${source}. Review details.`)}else toast('No public UPC match. Use label identification or manual entry.')}
['scanHeader','scanHome','scanNav'].forEach(id=>$('#'+id).onclick=startScan);$('#lookupManual').onclick=()=>lookup($('#manualUpc').value);$('#manualWine').onclick=()=>{closeD('scanDialog');editWine()};

function openLabel(){openD('labelDialog');$('#labelPhoto').value='';$('#labelPreview').classList.add('hidden');$('#readLabel').disabled=true;$('#identifyFastCork').disabled=true;$('#ocrStatus').textContent='Choose or take a clear, straight-on label photo.'}
$('#labelHome').onclick=openLabel;
$('#labelPhoto').onchange=e=>{labelFile=e.target.files[0];if(!labelFile)return;$('#labelPreview').src=URL.createObjectURL(labelFile);$('#labelPreview').classList.remove('hidden');$('#readLabel').disabled=false;$('#identifyFastCork').disabled=false};
function firstValue(obj,paths){for(const path of paths){const v=path.split('.').reduce((x,k)=>x?.[k],obj);if(v!==undefined&&v!==null&&v!=='')return v}return ''}
function cleanArray(v){return Array.isArray(v)?v.join(', '):(v||'')}
function applyFastCorkResult(raw){
 const w=raw?.results?.[0]?.wine||raw?.results?.[0]||raw?.results?.wine||raw?.results||raw?.wine||raw?.data?.wine||raw?.data||raw?.result||raw;
 if(!w||typeof w!=='object')throw new Error('FastCork result could not be read');
 const producer=firstValue(w,['producer','winery','winery_name','brand','brand_name','estate']);
 let name=firstValue(w,['full_wine_name','wine_name','product_name','label_name','name','title']);
 const vintageRaw=String(firstValue(w,['vintage','year'])||'');
 const vintage=vintageRaw.toLowerCase()==='unknown'?'':vintageRaw;
 const grapes=cleanArray(firstValue(w,['grapes','grape_varieties','grape_variety','varietals','varietal']));
 const region=firstValue(w,['region','origin']);
 const type=firstValue(w,['wine_type','type','style']);
 const price=firstValue(w,['average_retail_price_usd','average_price','price_usd','price']);
 const alcohol=firstValue(w,['alc_percentage','alcohol_percentage','abv','alcohol']);
 const tasting=firstValue(w,['tasting_notes','taste_profile','description']);
 const aroma=firstValue(w,['aroma','aromas','nose']);
 const pairing=cleanArray(firstValue(w,['food_pairing','food_pairings','pairings']));
 const serving=firstValue(w,['serving_temperature_celcius_range','serving_temperature','serving_temp']);
 const decant=firstValue(w,['decanting_time_minutes','decanting_minutes','decanting_time','decanting']);
 const wineryDescription=firstValue(w,['winery_description','producer_description']);
 const confidence=firstValue(w,['confidence','recognition_confidence','confidence_score']);
 if(!name)name=[producer,grapes].filter(Boolean).join(' ');
 setVal('wineName',name);setVal('producer',producer);setVal('vintage',vintage);setVal('varietal',grapes);setVal('region',region);setVal('appellation',firstValue(w,['appellation']));setVal('source','FastCork');
 if(type){const option=[...$('#wineType').options].find(o=>String(type).toLowerCase().includes(o.value.toLowerCase()));if(option)$('#wineType').value=option.value}
 if(price&&!isNaN(Number(price)))setVal('estimatedPrice',Number(price).toFixed(2));
 if(alcohol&&!isNaN(Number(alcohol)))setVal('alcoholPercentage',Number(alcohol));
 if(decant&&!isNaN(Number(decant)))setVal('decantingMinutes',Number(decant));
 if(confidence&&!isNaN(Number(confidence)))setVal('recognitionConfidence',Number(confidence));
 setVal('tastingNotes',[aroma?`Aroma: ${aroma}`:'',tasting?`Palate and finish: ${tasting}`:''].filter(Boolean).join('\n\n'));
 setVal('foodPairings',pairing);
 if(serving&&typeof serving==='object'){const min=serving.min_temp,max=serving.max_temp,metric=serving.metric||'°C';setVal('servingTemperature',min!==undefined&&max!==undefined?`${min}–${max}${metric}`:JSON.stringify(serving))}else setVal('servingTemperature',serving||'');
 setVal('servingGuidance',[decant?`Decant for approximately ${decant} minutes.`:'',wineryDescription?`Winery: ${wineryDescription}`:''].filter(Boolean).join('\n\n'));
 lastFastCorkRaw=raw;$('#advancedForm')?.classList.remove('hidden');if($('#toggleAdvancedForm'))$('#toggleAdvancedForm').textContent='Hide additional wine information';chooseBottlePhoto(labelFile)
}
async function callFastCork(file){const fd=new FormData();fd.append('file',file,file.name||'wine-label.jpg');fd.append('lang','en');const {data,error}=await db.functions.invoke('fastcork-analyze',{body:fd});if(error)throw new Error(error.message||'FastCork function failed');if(!data?.ok)throw new Error(data?.message||'FastCork unavailable');return data.result}
$('#identifyFastCork').onclick=async()=>{if(!labelFile)return;const btn=$('#identifyFastCork');btn.disabled=true;btn.textContent='Identifying wine…';$('#ocrStatus').textContent='Identifying label securely…';try{const result=await callFastCork(labelFile);closeD('labelDialog');editWine();applyFastCorkResult(result);toast('FastCork identified the label. Review before saving.')}catch(err){$('#ocrStatus').textContent=`FastCork unavailable: ${err.message}. Use on-device text extraction.`;toast(err.message)}finally{btn.disabled=false;btn.textContent='Identify wine with FastCork'}};
$('#readLabel').onclick=async()=>{if(!labelFile)return;$('#readLabel').disabled=true;$('#ocrStatus').textContent='Extracting text on this device…';try{const {data:{text}}=await Tesseract.recognize(labelFile,'eng',{logger:m=>{if(m.progress)$('#ocrStatus').textContent=`Reading label… ${Math.round(m.progress*100)}%`}});closeD('labelDialog');editWine();const lines=text.split(/\n/).map(x=>x.trim()).filter(x=>x.length>2),year=(text.match(/\b(19|20)\d{2}\b/)||[])[0];setVal('wineName',lines.slice(0,2).join(' '));setVal('vintage',year||'');setVal('notes',`Label text extracted:\n${text.trim()}`);setVal('source','On-device label OCR');chooseBottlePhoto(labelFile);toast('Label text extracted. Review the fields.')}catch(e){$('#ocrStatus').textContent='Could not read label: '+e.message}finally{$('#readLabel').disabled=false}};
async function testFastCork(){try{const {data,error}=await db.functions.invoke('fastcork-analyze',{body:{health:true}});if(error)throw error;$('#fastCorkStatus').textContent=data?.configured?'FastCork is configured and ready.':'FastCork is not configured. OCR and manual entry remain available.'}catch{$('#fastCorkStatus').textContent='FastCork Edge Function is unavailable. OCR and manual entry remain available.'}}
$('#testFastCork').onclick=testFastCork;
function renderRecommendations(){const rated=wines.filter(w=>w.personal_rating>=4);if(!rated.length){$('#recommendations').innerHTML='<div class="panel muted">Rate wines 4 or 5 stars to build recommendations.</div>';return}const count=a=>a.reduce((o,x)=>(x&&(o[x]=(o[x]||0)+1),o),{}),top=o=>Object.entries(o).sort((a,b)=>b[1]-a[1]).map(x=>x[0]),vars=top(count(rated.map(w=>w.varietal))),types=top(count(rated.map(w=>w.wine_type))),tags=top(count(rated.flatMap(w=>w.flavor_tags||[])));const ideas=[...vars.slice(0,3).map((x,i)=>({t:`Explore another ${x}`,s:96-i*4,w:`You rate ${x} highly. Look for ${tags.slice(0,3).join(', ')||'a similar profile'}.`})),...types.slice(0,2).map((x,i)=>({t:`Try a new ${x}`,s:89-i*3,w:`${x} is a top-rated household style.`}))];$('#recommendations').innerHTML=ideas.map(x=>`<div class="rec"><span class="rec-score">${x.s}% match</span><p class="eyebrow">PERSONALIZED IDEA</p><h3>${esc(x.t)}</h3><p>${esc(x.w)}</p></div>`).join('')}
$('#resetPassword').onclick=async()=>{const {error}=await db.auth.resetPasswordForEmail(user.email,{redirectTo:location.origin+location.pathname});toast(error?error.message:'Password reset email sent')};
boot();
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js'));
