const C = window.CELLAR_CONFIG || {};
const configured = C.SUPABASE_URL && C.SUPABASE_ANON_KEY && !C.SUPABASE_URL.includes("PASTE_") && !C.SUPABASE_ANON_KEY.includes("PASTE_");
const db = configured ? supabase.createClient(C.SUPABASE_URL, C.SUPABASE_ANON_KEY) : null;
let user = null, wines = [], transactions = [], settings = {}, scanner = null;
const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
const esc = v => String(v ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const money = n => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n||0));
const stars = n => `<span class="stars">${'★'.repeat(Math.round(Number(n||0)))}${'☆'.repeat(5-Math.round(Number(n||0)))}</span>`;
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
function openDialog(id){const d=$('#'+id);if(!d.open)d.showModal()}
function closeDialog(id){const d=$('#'+id);if(d.open)d.close();if(id==='scanDialog')stopScanner()}
$$('[data-close]').forEach(b=>b.onclick=()=>closeDialog(b.dataset.close));

async function boot(){
  if(!configured){$('#configWarning').classList.remove('hidden');return}
  const {data:{session}}=await db.auth.getSession();
  if(session) await enterApp(session.user);
  db.auth.onAuthStateChange(async(_,session)=>{ if(session?.user && !user) await enterApp(session.user); if(!session){user=null;showAuth()} });
}
function showAuth(){ $('#authScreen').classList.remove('hidden');$('#app').classList.add('hidden') }
async function enterApp(u){user=u;$('#authScreen').classList.add('hidden');$('#app').classList.remove('hidden');await loadAll();showView('home')}
$('#loginForm').onsubmit=async e=>{e.preventDefault();if(!db)return toast('Configure Supabase first');const email=$('#emailInput').value.trim();const {error}=await db.auth.signInWithPassword({
  email,
  password
});if(error)toast(error.message);else toast('Check your email for the sign-in link')};
$('#signOutBtn').onclick=()=>db.auth.signOut();

async function loadAll(){
  const [wr,tr,sr]=await Promise.all([
    db.from('wines').select('*').order('created_at',{ascending:false}),
    db.from('inventory_transactions').select('*').order('created_at',{ascending:false}).limit(25),
    db.from('user_settings').select('*').maybeSingle()
  ]);
  if(wr.error)return toast(wr.error.message);wines=wr.data||[];transactions=tr.data||[];settings=sr.data||{};renderAll();
}
function showView(name){$$('.view').forEach(v=>v.classList.remove('active'));$('#'+name+'View').classList.add('active');$$('.bottom-nav [data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));if(name==='discover')renderRecommendations()}
$$('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));

function wineCard(w){const img=w.image_url?`<img class="bottle-img" src="${esc(w.image_url)}" alt="">`:`<div class="bottle-img placeholder-img">🍷</div>`;return `<button class="wine-card" data-wine="${w.id}">${img}<div><span class="eyebrow">${esc(w.producer||w.wine_type||'WINE')}</span><h3>${esc(w.name)}</h3><p>${esc([w.vintage,w.varietal,w.region].filter(Boolean).join(' · '))}</p>${stars(w.personal_rating)}</div><div class="card-side"><span class="badge ${w.quantity?'':'zero'}">${w.quantity} left</span><p class="price">${money(w.estimated_price||w.purchase_price)}</p></div></button>`}
function renderAll(){
  const bottles=wines.reduce((s,w)=>s+Number(w.quantity||0),0), value=wines.reduce((s,w)=>s+Number(w.quantity||0)*Number(w.estimated_price||w.purchase_price||0),0), low=wines.filter(w=>Number(w.quantity)<Number(w.target_quantity) && Number(w.personal_rating)>=3);
  $('#statBottles').textContent=bottles;$('#statWines').textContent=wines.filter(w=>w.quantity>0).length;$('#statValue').textContent=money(value);$('#lowCount').textContent=low.length?`${low.length} favorite${low.length===1?' is':'s are'} low`:'Nothing is low';
  $('#homeLowList').innerHTML=low.slice(0,3).map(wineCard).join('')||'<div class="empty"><p>No low-stock favorites yet.</p></div>';
  $('#activityList').innerHTML=transactions.slice(0,5).map(t=>`<div class="activity-item"><b>${esc(t.transaction_type)}</b> ${Math.abs(t.quantity_change)} bottle(s)${t.notes?` · ${esc(t.notes)}`:''}<time>${new Date(t.created_at).toLocaleString()}</time></div>`).join('')||'<p class="muted">Activity appears after bottles are added or consumed.</p>';
  renderCellar();renderShopping();renderSettings();bindWineCards();
}
function renderCellar(){const q=$('#searchInput').value.toLowerCase(),type=$('#typeFilter').value;const list=wines.filter(w=>(type==='All'||w.wine_type===type)&&[w.name,w.producer,w.region,w.varietal].join(' ').toLowerCase().includes(q));$('#wineList').innerHTML=list.map(wineCard).join('');$('#emptyCellar').classList.toggle('hidden',wines.length>0);bindWineCards()}
$('#searchInput').oninput=renderCellar;$('#typeFilter').onchange=renderCellar;
function bindWineCards(){$$('[data-wine]').forEach(b=>b.onclick=()=>openDetail(b.dataset.wine))}
function renderShopping(){const low=wines.filter(w=>Number(w.quantity)<Number(w.target_quantity)).sort((a,b)=>(b.personal_rating||0)-(a.personal_rating||0));$('#shoppingList').innerHTML=low.map(w=>`<div class="shopping-card"><span class="badge">BUY ${w.target_quantity-w.quantity}</span><h3>${esc(w.producer||'')} ${esc(w.name)}</h3><p>Have ${w.quantity} · Target ${w.target_quantity}</p><p class="price">About ${money(w.estimated_price||w.purchase_price)} each</p><button class="secondary" data-restock="${w.id}">Add one to fridge</button></div>`).join('')||'<div class="empty"><span>✓</span><h3>Your fridge is stocked</h3><p>No wine is below its target quantity.</p></div>';$$('[data-restock]').forEach(b=>b.onclick=()=>adjustQuantity(b.dataset.restock,1,'restocked'))}
$('#copyShopping').onclick=async()=>{const low=wines.filter(w=>w.quantity<w.target_quantity);const text=low.length?low.map(w=>`${w.target_quantity-w.quantity} x ${w.producer||''} ${w.name} (${money(w.estimated_price||w.purchase_price)} each)`).join('\n'):'Wine fridge is fully stocked.';await navigator.clipboard.writeText(text);toast('Shopping list copied')};
function renderSettings(){$('#displayName').value=settings.display_name||'';$('#favoriteRetailer').value=settings.favorite_retailer||'';$('#priceCeiling').value=settings.recommendation_price_ceiling??75}
$('#settingsForm').onsubmit=async e=>{e.preventDefault();const payload={user_id:user.id,display_name:$('#displayName').value.trim(),favorite_retailer:$('#favoriteRetailer').value.trim(),recommendation_price_ceiling:Number($('#priceCeiling').value||0),updated_at:new Date().toISOString()};const {error}=await db.from('user_settings').upsert(payload);if(error)return toast(error.message);settings=payload;toast('Settings saved')};

function openDetail(id){const w=wines.find(x=>x.id===id);if(!w)return;const flavors=(w.flavor_tags||[]).map(x=>`<span>${esc(x)}</span>`).join('');$('#detailContent').innerHTML=`<div class="sheet-head"><div><p class="eyebrow">${esc(w.producer||w.wine_type)}</p><h2>${esc(w.name)}</h2></div><button class="close-btn" onclick="document.querySelector('#detailDialog').close()">×</button></div><div class="detail-hero"><p>${esc([w.vintage,w.varietal,w.region,w.country].filter(Boolean).join(' · '))}</p><h2>${stars(w.personal_rating)}</h2><p>${esc(w.personal_notes||'No personal tasting notes yet.')}</p></div><div class="detail-grid"><div class="detail-stat"><b>${w.quantity}</b><span>In fridge</span></div><div class="detail-stat"><b>${w.external_rating||'—'}</b><span>${esc(w.external_source||'Source score')}</span></div><div class="detail-stat"><b>${money(w.estimated_price||w.purchase_price)}</b><span>Approx. price</span></div></div><div class="flavors">${flavors}</div><p class="muted">Rack ${esc(w.rack_location||'not set')} · Body ${w.body_score}/5 · Sweetness ${w.sweetness_score}/5 · Acidity ${w.acidity_score}/5 · Tannin ${w.tannin_score}/5</p><div class="detail-actions"><button class="secondary" id="editCurrent">Edit details</button><button class="primary" id="consumeCurrent" ${w.quantity<1?'disabled':''}>Mark consumed</button></div>`;openDialog('detailDialog');$('#editCurrent').onclick=()=>{closeDialog('detailDialog');openWineForm(w)};$('#consumeCurrent').onclick=async()=>{await adjustQuantity(w.id,-1,'consumed');closeDialog('detailDialog')}}
async function adjustQuantity(id,delta,type){const w=wines.find(x=>x.id===id);if(!w||w.quantity+delta<0)return;const {error}=await db.from('wines').update({quantity:w.quantity+delta,updated_at:new Date().toISOString()}).eq('id',id);if(error)return toast(error.message);await db.from('inventory_transactions').insert({user_id:user.id,wine_id:id,transaction_type:type,quantity_change:delta,notes:w.name});await loadAll();toast(delta>0?'Bottle added':'Bottle marked consumed')}

function resetWineForm(){ $('#wineForm').reset();$('#wineId').value='';$('#imageUrl').value='';$('#quantity').value=1;$('#targetQuantity').value=2;$('#bodyScore').value=3;$('#sweetnessScore').value=2;$('#acidityScore').value=3;$('#tanninScore').value=3;$('#deleteWine').classList.add('hidden');$('#formEyebrow').textContent='ADD BOTTLE'; }
function openWineForm(w=null){resetWineForm();if(w){$('#formEyebrow').textContent='EDIT WINE';$('#wineId').value=w.id;$('#imageUrl').value=w.image_url||'';$('#wineName').value=w.name||'';$('#producer').value=w.producer||'';$('#vintage').value=w.vintage||'';$('#wineType').value=w.wine_type||'Other';$('#varietal').value=w.varietal||'';$('#country').value=w.country||'';$('#region').value=w.region||'';$('#upc').value=w.upc||'';$('#rack').value=w.rack_location||'';$('#quantity').value=w.quantity;$('#targetQuantity').value=w.target_quantity;$('#purchasePrice').value=w.purchase_price||'';$('#estimatedPrice').value=w.estimated_price||'';$('#externalSource').value=w.external_source||'';$('#externalRating').value=w.external_rating||'';$('#personalRating').value=w.personal_rating||0;$('#bodyScore').value=w.body_score||3;$('#sweetnessScore').value=w.sweetness_score||2;$('#acidityScore').value=w.acidity_score||3;$('#tanninScore').value=w.tannin_score||3;$('#flavorTags').value=(w.flavor_tags||[]).join(', ');$('#personalNotes').value=w.personal_notes||'';$('#deleteWine').classList.remove('hidden')}openDialog('wineDialog')}
$('#wineForm').onsubmit=async e=>{e.preventDefault();const id=$('#wineId').value;const payload={user_id:user.id,name:$('#wineName').value.trim(),producer:$('#producer').value.trim(),vintage:$('#vintage').value.trim(),wine_type:$('#wineType').value,varietal:$('#varietal').value.trim(),country:$('#country').value.trim(),region:$('#region').value.trim(),upc:$('#upc').value.trim()||null,rack_location:$('#rack').value.trim(),quantity:Number($('#quantity').value),target_quantity:Number($('#targetQuantity').value),purchase_price:Number($('#purchasePrice').value)||null,estimated_price:Number($('#estimatedPrice').value)||null,external_source:$('#externalSource').value.trim(),external_rating:Number($('#externalRating').value)||null,personal_rating:Number($('#personalRating').value),body_score:Number($('#bodyScore').value),sweetness_score:Number($('#sweetnessScore').value),acidity_score:Number($('#acidityScore').value),tannin_score:Number($('#tanninScore').value),flavor_tags:$('#flavorTags').value.split(',').map(x=>x.trim()).filter(Boolean),personal_notes:$('#personalNotes').value.trim(),image_url:$('#imageUrl').value||null,updated_at:new Date().toISOString()};let res;if(id)res=await db.from('wines').update(payload).eq('id',id);else res=await db.from('wines').insert(payload).select().single();if(res.error)return toast(res.error.message);if(!id)await db.from('inventory_transactions').insert({user_id:user.id,wine_id:res.data.id,transaction_type:'added',quantity_change:payload.quantity,notes:payload.name});closeDialog('wineDialog');await loadAll();toast(id?'Wine updated':'Wine added to fridge')};
$('#deleteWine').onclick=async()=>{const id=$('#wineId').value;if(!id||!confirm('Delete this wine and its history?'))return;const {error}=await db.from('wines').delete().eq('id',id);if(error)return toast(error.message);closeDialog('wineDialog');await loadAll();toast('Wine deleted')};

async function startScanner(){openDialog('scanDialog');$('#scanStatus').textContent='Starting camera…';if(typeof Html5QrcodeScanner==='undefined'){return $('#scanStatus').textContent='Scanner library did not load. Enter the UPC manually.'}scanner=new Html5QrcodeScanner('reader',{fps:10,qrbox:{width:260,height:130},rememberLastUsedCamera:true,supportedScanTypes:[Html5QrcodeScanType.SCAN_TYPE_CAMERA]},false);scanner.render(async text=>{await stopScanner();$('#scanStatus').textContent=`Found ${text}. Looking it up…`;await lookupBarcode(text)},()=>{})}
async function stopScanner(){if(scanner){try{await scanner.clear()}catch{}scanner=null}$('#reader').innerHTML=''}
async function lookupBarcode(code){code=String(code).replace(/\D/g,'');if(!code)return toast('Enter a valid UPC');try{const r=await fetch(`https://world.openfoodfacts.org/api/v2/product/${encodeURIComponent(code)}.json?fields=product_name,brands,categories,countries,origins,image_front_url`);const j=await r.json();closeDialog('scanDialog');openWineForm();$('#upc').value=code;if(j.status===1&&j.product){const p=j.product;$('#wineName').value=p.product_name||'';$('#producer').value=(p.brands||'').split(',')[0];$('#country').value=(p.countries||'').split(',')[0];$('#region').value=p.origins||'';$('#imageUrl').value=p.image_front_url||'';$('#externalSource').value='Open Food Facts';toast('Wine found. Review and complete the details.')}else{toast('UPC not found. Add the wine manually.')}}catch(e){closeDialog('scanDialog');openWineForm();$('#upc').value=code;toast('Lookup unavailable. Enter the details manually.')}}
['scanTop','scanHome','scanNav'].forEach(id=>$('#'+id).onclick=startScanner);$('#emptyAdd').onclick=()=>openWineForm();$('#manualAdd').onclick=()=>{closeDialog('scanDialog');openWineForm()};$('#lookupUpc').onclick=()=>lookupBarcode($('#manualUpc').value);

function renderRecommendations(){const rated=wines.filter(w=>w.personal_rating>=4);if(!rated.length){$('#recommendations').innerHTML='<div class="empty"><span>★</span><h3>Rate a few wines first</h3><p>Give wines 4 or 5 stars and recommendations will appear here.</p></div>';return}const types=count(rated.map(w=>w.wine_type)),vars=count(rated.map(w=>w.varietal).filter(Boolean)),tags=count(rated.flatMap(w=>w.flavor_tags||[]));const top=(o,n=3)=>Object.entries(o).sort((a,b)=>b[1]-a[1]).slice(0,n).map(x=>x[0]);const ideas=[];top(vars,3).forEach((v,i)=>ideas.push({title:`Explore another ${v}`,score:96-i*4,why:`You consistently rate ${v} wines highly. Look for ${top(tags,3).join(', ')||'a similar flavor profile'}.`}));top(types,3).forEach((t,i)=>ideas.push({title:`Try a new ${t} wine`,score:90-i*3,why:`${t} is one of your highest-rated styles. Stay near your preferred ceiling of ${money(settings.recommendation_price_ceiling||75)}.`}));$('#recommendations').innerHTML=ideas.slice(0,5).map(x=>`<div class="rec-card"><span class="rec-score">${x.score}% match</span><p class="eyebrow">PERSONALIZED IDEA</p><h3>${esc(x.title)}</h3><p>${esc(x.why)}</p></div>`).join('')}
function count(arr){return arr.reduce((o,x)=>(o[x]=(o[x]||0)+1,o),{})}
boot();
if('serviceWorker' in navigator) window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js'));
