-- Cellar Notes Supabase setup
-- Run this entire file once in Supabase Dashboard > SQL Editor.
-- Safe to re-run: tables, indexes, policies, and trigger are created idempotently.

create extension if not exists pgcrypto;

create table if not exists public.wines (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  upc text,
  name text not null,
  producer text,
  vintage text,
  wine_type text not null default 'Other' check (wine_type in ('Red','White','Rosé','Sparkling','Dessert','Other')),
  varietal text,
  country text,
  region text,
  rack_location text,
  quantity integer not null default 0 check (quantity >= 0),
  target_quantity integer not null default 2 check (target_quantity >= 0),
  purchase_price numeric(10,2) check (purchase_price is null or purchase_price >= 0),
  estimated_price numeric(10,2) check (estimated_price is null or estimated_price >= 0),
  image_url text,
  external_source text,
  external_rating numeric(5,2) check (external_rating is null or external_rating between 0 and 100),
  personal_rating numeric(2,1) not null default 0 check (personal_rating between 0 and 5),
  body_score smallint not null default 3 check (body_score between 1 and 5),
  sweetness_score smallint not null default 2 check (sweetness_score between 1 and 5),
  acidity_score smallint not null default 3 check (acidity_score between 1 and 5),
  tannin_score smallint not null default 3 check (tannin_score between 1 and 5),
  flavor_tags text[] not null default '{}',
  personal_notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.inventory_transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  wine_id uuid not null references public.wines(id) on delete cascade,
  transaction_type text not null check (transaction_type in ('added','restocked','consumed','gifted','removed','adjustment')),
  quantity_change integer not null,
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.user_settings (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  favorite_retailer text,
  recommendation_price_ceiling numeric(10,2) not null default 75,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists wines_user_upc_unique on public.wines(user_id, upc) where upc is not null;
create index if not exists wines_user_quantity_idx on public.wines(user_id, quantity);
create index if not exists wines_user_rating_idx on public.wines(user_id, personal_rating desc);
create index if not exists transactions_user_created_idx on public.inventory_transactions(user_id, created_at desc);

alter table public.wines enable row level security;
alter table public.inventory_transactions enable row level security;
alter table public.user_settings enable row level security;

-- Drop/recreate policies so this script can be safely updated and re-run.
drop policy if exists "Users manage their wines" on public.wines;
create policy "Users manage their wines" on public.wines for all
to authenticated using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Users manage their transactions" on public.inventory_transactions;
create policy "Users manage their transactions" on public.inventory_transactions for all
to authenticated using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Users manage their settings" on public.user_settings;
create policy "Users manage their settings" on public.user_settings for all
to authenticated using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

-- Prevent a transaction from being created against another user's wine.
create or replace function public.validate_transaction_owner()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if not exists (select 1 from public.wines where id = new.wine_id and user_id = new.user_id) then
    raise exception 'Wine does not belong to this user';
  end if;
  return new;
end;
$$;

drop trigger if exists validate_transaction_owner_trigger on public.inventory_transactions;
create trigger validate_transaction_owner_trigger
before insert or update on public.inventory_transactions
for each row execute function public.validate_transaction_owner();

grant usage on schema public to authenticated;
grant select, insert, update, delete on public.wines to authenticated;
grant select, insert, update, delete on public.inventory_transactions to authenticated;
grant select, insert, update, delete on public.user_settings to authenticated;
grant usage, select on all sequences in schema public to authenticated;
